### ISSUE TITLE
Why MOE does not support Linux (Ubuntu)?

### ISSUE THREAD

**Issue by BigGitWorld** [multi-os-engine/multi-os-engine#135] opened 2020-03-30 07:52 UTC
I'd like to test MOE but it has very limitations such as:
- MOE does not support Linux.
why? and when do you think support Linux too?

Please clarify us...
thank you

**Comment by kisg** [comment] 2020-03-30 11:27
This is a duplicate of #34 

I wrote a bit more details about this in the forum:
https://discuss.multi-os-engine.org/t/moe-finally-supports-linux-or-not/2780/2

**Closed by kisg** 2020-03-30 11:27 UTC
